spring:
  application:
    name: travel-feign
  cloud:
    nacos:
      discovery:
        server-addr: ${server-addr}:8848
        # username: nacos
        # password: nacos

      config:
        server-addr: ${server-addr}:8848
        file-extension: yaml
        # ?? import ???????? optional ???????
        import-check:
          enabled: false

server:
  port: 18005
