spring:
  application:
    name: travel-user
  cloud:
    nacos:
      discovery:
        server-addr: ${server-addr}:8848
        username: nacos
        password: nacos
      config:
        server-addr: ${server-addr}:8848
        file-extension: yaml
        refresh-enabled: true
        import-check:
          enabled: false   # 👈 修正这里
  datasource:
      url: jdbc:postgresql://localhost:5432/smart_travel
      username: postgres
      password: postgres
      driver-class-name: org.postgresql.Driver
    #    url: jdbc:mysql://localhost:3306/smart_travel?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    #    username: root
    #    password: 123456
    #    driver-class-name: com.mysql.cj.jdbc.Driver

server:
  port: 18001

# mybatis-plus 基本配置
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl   # 开发阶段打印 sql，生产去掉
  global-config:
    db-config:
      id-type: auto                  # 主键自增
      logic-delete-field: deleted    # 逻辑删除字段（可选）
      logic-delete-value: 1
      logic-not-delete-value: 0

# 开启 feign
#feign:
#  client:
#    config:
#      default:
#        connectTimeout: 5000
#        readTimeout: 5000

springdoc:
  swagger-ui:
    path: /swagger-ui.html          # 原生 UI
  api-docs:
    path: /v3/api-docs

knife4j:
  enable: true
  setting:
    language: zh-CN
    enable-swagger-models: true
    enable-footer: false

logging:
  level:
    com.alibaba.nacos: ERROR
    org.springframework.cloud.client.discovery: ERROR

jwt:
  # Base64字符串
  secret: HPJigY187DIyTDySldz1rCJSfZTe2H+Hr8cFc8G7yqc=
  issuer: smart-travel