-- 1. 创建表（使用 GENERATED BY DEFAULT AS IDENTITY 替代 AUTO_INCREMENT）
CREATE TABLE orders (
                        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        order_no VARCHAR(64) NOT NULL,
                        user_id BIGINT NOT NULL,
                        username VARCHAR(64) NOT NULL,
                        order_type VARCHAR(32) NOT NULL,
                        amount DECIMAL(10,2) NOT NULL,
                        status VARCHAR(32) NOT NULL DEFAULT '待支付',
                        departure VARCHAR(64),
                        arrival VARCHAR(64),
                        departure_time TIMESTAMP,
                        create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                        update_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                        deleted SMALLINT NOT NULL DEFAULT 0
);

-- 2. 添加表与列的注释
COMMENT ON TABLE orders IS '订单表';
COMMENT ON COLUMN orders.id IS '主键ID';
COMMENT ON COLUMN orders.order_no IS '订单号（唯一）';
COMMENT ON COLUMN orders.user_id IS '下单用户ID';
COMMENT ON COLUMN orders.username IS '用户名（冗余）';
COMMENT ON COLUMN orders.order_type IS '订单类型：flight/hotel/train/car';
COMMENT ON COLUMN orders.amount IS '订单金额';
COMMENT ON COLUMN orders.status IS '状态：待支付/已支付/已完成/已取消';
COMMENT ON COLUMN orders.departure IS '出发地';
COMMENT ON COLUMN orders.arrival IS '目的地';
COMMENT ON COLUMN orders.departure_time IS '出发时间';
COMMENT ON COLUMN orders.create_time IS '创建时间';
COMMENT ON COLUMN orders.update_time IS '更新时间';
COMMENT ON COLUMN orders.deleted IS '逻辑删除：0正常 1删除';

-- 3. 添加唯一约束（使用命名约束，与 MySQL 的 uk_order_no 对应）
ALTER TABLE orders ADD CONSTRAINT uk_order_no UNIQUE (order_no);

-- 4. 创建普通索引
CREATE INDEX idx_user_id ON orders (user_id);
CREATE INDEX idx_order_type ON orders (order_type);
CREATE INDEX idx_status ON orders (status);

-- 5. 创建触发器，模拟 MySQL 的 ON UPDATE CURRENT_TIMESTAMP
--    (当行更新时自动将 update_time 设为当前时间)
CREATE OR REPLACE FUNCTION update_orders_update_time()
RETURNS TRIGGER AS $$
BEGIN
    NEW.update_time = CURRENT_TIMESTAMP;
RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trigger_update_orders_update_time
    BEFORE UPDATE ON orders
    FOR EACH ROW
    EXECUTE FUNCTION update_orders_update_time();