-- ================================================
-- Smart Travel 数据库初始化脚本
-- 基于 Entity 实体类生成（表名统一使用复数形式）
-- ================================================

-- ================================================
-- 1. 创建数据库（如果不存在）
-- ================================================
SELECT 'CREATE DATABASE smart_travel'
WHERE NOT EXISTS (SELECT FROM pg_database WHERE datname = 'smart_travel')\gexec

-- 连接数据库
\c smart_travel

-- ================================================
-- 2. 启用扩展（pgvector 用于向量存储）
-- ================================================
CREATE EXTENSION IF NOT EXISTS vector;

-- ================================================
-- 3. 建表 DDL（所有表 + 索引）
-- ================================================

-- 用户表
CREATE TABLE IF NOT EXISTS users (
                                     id BIGINT PRIMARY KEY,
                                     username VARCHAR(64) UNIQUE NOT NULL,
                                     password VARCHAR(255) NOT NULL,
                                     email VARCHAR(128),
                                     phone VARCHAR(32),
                                     create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                                     update_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                                     deleted INTEGER DEFAULT 0,
                                     roles VARCHAR(255) NOT NULL,
                                     company_id BIGINT
);
CREATE INDEX idx_user_username ON users(username);
CREATE INDEX idx_user_email ON users(email);
CREATE INDEX idx_user_phone ON users(phone);
CREATE INDEX idx_user_create_time ON users(create_time);
CREATE INDEX idx_user_update_time ON users(update_time);
CREATE INDEX idx_user_deleted ON users(deleted);
CREATE INDEX idx_user_company_id ON users(company_id);

-- 企业表
CREATE TABLE IF NOT EXISTS company (
                                       id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                       name VARCHAR(128) NOT NULL,
                                       description TEXT,
                                       auto_approve BOOLEAN DEFAULT FALSE,
                                       user_name VARCHAR(100) UNIQUE,
                                       password VARCHAR(255) NOT NULL,
                                       over_amount_must_audit decimal(18, 2) DEFAULT 0.0 NOT NULL,
                                       create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                                       update_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                                       deleted INTEGER DEFAULT 0
);
CREATE INDEX idx_company_name ON company(name);
CREATE INDEX idx_company_user_name ON company(user_name);
CREATE INDEX idx_company_create_time ON company(create_time);
CREATE INDEX idx_company_update_time ON company(update_time);

-- 部门表（树形结构）
CREATE TABLE IF NOT EXISTS departments (
                                           id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                           parent_id BIGINT DEFAULT 0,
                                           company_id BIGINT NOT NULL,
                                           name VARCHAR(128) NOT NULL,
                                           description TEXT,
                                           create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                                           update_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                                           deleted INTEGER DEFAULT 0,
                                           CONSTRAINT fk_dept_parent FOREIGN KEY (parent_id) REFERENCES departments(id),
                                           CONSTRAINT fk_dept_company FOREIGN KEY (company_id) REFERENCES company(id)
);
CREATE INDEX idx_dept_company_id ON departments(company_id);
CREATE INDEX idx_dept_parent_id ON departments(parent_id);
CREATE INDEX idx_dept_name ON departments(name);
CREATE INDEX idx_dept_create_time ON departments(create_time);
CREATE INDEX idx_dept_update_time ON departments(update_time);

-- 员工表
CREATE TABLE IF NOT EXISTS employees (
                                         id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                         name VARCHAR(100),
                                         company_id BIGINT NOT NULL,
                                         department_id BIGINT,
                                         user_id BIGINT UNIQUE NOT NULL,
                                         position VARCHAR(64),
                                         employee_no VARCHAR(64),
                                         entry_date DATE,
                                         is_primary BOOLEAN DEFAULT TRUE,
                                         create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                                         update_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                                         deleted INTEGER DEFAULT 0,
                                         CONSTRAINT fk_emp_company FOREIGN KEY (company_id) REFERENCES company(id),
                                         CONSTRAINT fk_emp_dept FOREIGN KEY (department_id) REFERENCES departments(id),
                                         CONSTRAINT fk_emp_user FOREIGN KEY (user_id) REFERENCES users(id)
);
CREATE INDEX idx_employee_name ON employees(name);
CREATE INDEX idx_employee_user_id ON employees(user_id);
CREATE INDEX idx_employee_company_id ON employees(company_id);
CREATE INDEX idx_employee_dept_id ON employees(department_id);
CREATE INDEX idx_employee_employee_no ON employees(employee_no);
CREATE INDEX idx_employee_create_time ON employees(create_time);
CREATE INDEX idx_employee_update_time ON employees(update_time);


-- 审批记录表
CREATE TABLE IF NOT EXISTS approvals (
                                         id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                         order_no VARCHAR(64) UNIQUE NOT NULL,
                                         company_id BIGINT NOT NULL,
                                         applicant_id BIGINT,
                                         approver_id BIGINT,
                                         status VARCHAR(32),
                                         trip_items JSONB DEFAULT '[]',
                                         reason VARCHAR(500),
                                         remark TEXT,
                                         create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                                         update_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                                         deleted INTEGER DEFAULT 0,
                                         CONSTRAINT fk_approval_company FOREIGN KEY (company_id) REFERENCES company(id),
                                         CONSTRAINT fk_approval_applicant_ename FOREIGN KEY (applicant_id) REFERENCES employees(id),
                                         CONSTRAINT fk_approval_approver_ename FOREIGN KEY (approver_id) REFERENCES employees(id)
);
CREATE INDEX idx_approval_order_no ON approvals(order_no);
CREATE INDEX idx_approval_company_id ON approvals(company_id);
CREATE INDEX idx_approval_applicant_id ON approvals(applicant_id);
CREATE INDEX idx_approval_approver_id ON approvals(approver_id);
CREATE INDEX idx_approval_status ON approvals(status);
CREATE INDEX idx_approval_create_time ON approvals(create_time);
CREATE INDEX idx_approval_update_time ON approvals(update_time);

-- 订单主表
CREATE TABLE IF NOT EXISTS orders (
                                      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                      company_id BIGINT NOT NULL,
                                      order_no VARCHAR(64) UNIQUE NOT NULL,
                                      user_id BIGINT NOT NULL,
                                      username VARCHAR(64),
                                      order_type VARCHAR(32) NOT NULL,
                                      amount DECIMAL(12,2) NOT NULL,
                                      status VARCHAR(32) DEFAULT 'PENDING_PAYMENT',
                                      audit_status VARCHAR(32) DEFAULT 'PENDING',
                                      pay_time TIMESTAMP,
                                      pay_type VARCHAR(32),
                                      refundable BOOLEAN DEFAULT TRUE,
                                      refund_amount DECIMAL(12,2) DEFAULT 0,
                                      journey JSONB,
                                      create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                                      update_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                                      deleted INTEGER DEFAULT 0,
                                      approval_id BIGINT NOT NULL,
                                      order_requirements TEXT DEFAULT NULL,
                                      remark VARCHAR(255),
                                      CONSTRAINT fk_order_company FOREIGN KEY (company_id) REFERENCES company(id),
                                      CONSTRAINT fk_order_user FOREIGN KEY (user_id) REFERENCES users(id),
                                      CONSTRAINT fk_order_approval FOREIGN KEY (approval_id) REFERENCES approvals(id)
);
CREATE INDEX idx_order_user_id ON orders(user_id);
CREATE INDEX idx_order_company_id ON orders(company_id);
CREATE INDEX idx_order_status ON orders(status);
CREATE INDEX idx_order_audit_status ON orders(audit_status);
CREATE INDEX idx_order_type ON orders(order_type);
CREATE INDEX idx_order_no ON orders(order_no);
CREATE INDEX idx_order_approval_id ON orders(approval_id);
CREATE INDEX idx_order_create_time ON orders(create_time);
CREATE INDEX idx_order_update_time ON orders(update_time);

-- 行程段表（多段行程）
CREATE TABLE IF NOT EXISTS journeys (
                                        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                        order_id BIGINT NOT NULL,
                                        company_id BIGINT NOT NULL,
                                        flight_no VARCHAR(32),
                                        train_no VARCHAR(32),
                                        hotel_name VARCHAR(128),
                                        car_no VARCHAR(32),
                                        departure VARCHAR(128),
                                        arrival VARCHAR(128),
                                        departure_time TIMESTAMP,
                                        arrival_time TIMESTAMP,
                                        tickets JSONB,
                                        create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                                        update_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                                        deleted INTEGER DEFAULT 0,
                                        trip_type varchar(50) NOT NULL,
                                        airline VARCHAR(100),
                                        cabin_class VARCHAR(50),
                                        CONSTRAINT fk_journey_order FOREIGN KEY (order_id) REFERENCES orders(id),
                                        CONSTRAINT fk_journey_company FOREIGN KEY (company_id) REFERENCES company(id)
);
CREATE INDEX idx_journey_order_id ON journeys(order_id);
CREATE INDEX idx_journey_company_id ON journeys(company_id);
CREATE INDEX idx_journey_flight_no ON journeys(flight_no);
CREATE INDEX idx_journey_train_no ON journeys(train_no);
CREATE INDEX idx_journey_hotel_name ON journeys(hotel_name);
CREATE INDEX idx_journey_car_no ON journeys(car_no);
CREATE INDEX idx_journey_create_time ON journeys(create_time);
CREATE INDEX idx_journey_update_time ON journeys(update_time);
CREATE INDEX idx_journey_trip_type ON journeys(trip_type);

-- 乘客表（常用乘客）
CREATE TABLE IF NOT EXISTS passengers (
                                          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                          name VARCHAR(64) NOT NULL,
                                          gender VARCHAR(8),
                                          birthday VARCHAR(20),
                                          phone VARCHAR(32),
                                          id_type VARCHAR(32),
                                          id_number VARCHAR(64),
                                          company_id BIGINT,
                                          user_id BIGINT,
                                          create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                                          update_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                                          deleted INTEGER DEFAULT 0,
                                          CONSTRAINT fk_passenger_company FOREIGN KEY (company_id) REFERENCES company(id),
                                          CONSTRAINT fk_passenger_user FOREIGN KEY (user_id) REFERENCES users(id)
);
CREATE INDEX idx_passenger_user_id ON passengers(user_id);
CREATE INDEX idx_passenger_id_type ON passengers(id_type);
CREATE INDEX idx_passenger_id_number ON passengers(id_number);
CREATE INDEX idx_passenger_phone ON passengers(phone);
CREATE INDEX idx_passenger_company_id ON passengers(company_id);
CREATE INDEX idx_passenger_name ON passengers(name);
CREATE INDEX idx_passenger_create_time ON passengers(create_time);
CREATE INDEX idx_passenger_update_time ON passengers(update_time);

-- 票务明细表
CREATE TABLE IF NOT EXISTS tickets (
                                       id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                       journey_id BIGINT NOT NULL,
                                       card_no VARCHAR(64),
                                       travel_type VARCHAR(32),
                                       departure VARCHAR(128),
                                       arrival VARCHAR(128),
                                       departure_time TIMESTAMP,
                                       arrival_time TIMESTAMP,
                                       company_id BIGINT,
                                       passenger_id BIGINT,
                                       passenger_name VARCHAR(64),
                                       has_child BOOLEAN DEFAULT FALSE,
                                       child_age INTEGER,
                                       has_baby BOOLEAN DEFAULT FALSE,
                                       baby_age INTEGER,
                                       has_pet BOOLEAN DEFAULT FALSE,
                                       pet_type VARCHAR(32),
                                       amount DECIMAL(12,2),
                                       price DECIMAL(12,2),
                                       tax_fee DECIMAL(12,2),
                                       insurance_fee DECIMAL(12,2),
                                       create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                                       update_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                                       deleted INTEGER DEFAULT 0,
                                       CONSTRAINT fk_ticket_journey FOREIGN KEY (journey_id) REFERENCES journeys(id),
                                       CONSTRAINT fk_ticket_company FOREIGN KEY (company_id) REFERENCES company(id),
                                       CONSTRAINT fk_ticket_passenger FOREIGN KEY (passenger_id) REFERENCES passengers(id)
);
CREATE INDEX idx_ticket_journey_id ON tickets(journey_id);
CREATE INDEX idx_ticket_company_id ON tickets(company_id);
CREATE INDEX idx_ticket_passenger_id ON tickets(passenger_id);
CREATE INDEX idx_ticket_card_no ON tickets(card_no);
CREATE INDEX idx_ticket_travel_type ON tickets(travel_type);
CREATE INDEX idx_ticket_create_time ON tickets(create_time);
CREATE INDEX idx_ticket_update_time ON tickets(update_time);


-- 差标标准表
CREATE TABLE IF NOT EXISTS standards (
                                         id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                         company_id BIGINT NOT NULL,
                                         name VARCHAR(128),
                                         content TEXT,
                                         flight_max_price DECIMAL(10,2) default 3000,
                                         hotel_max_price DECIMAL(10,2) default 1000,
                                         train_max_price DECIMAL(10,2) default 800,
                                         car_max_price DECIMAL(10,2) default 200,
                                         month_max_price DECIMAL(10,2) default 5000,
                                         year_max_price DECIMAL(10,2) default 20000,
                                         description TEXT,
                                         create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                                         update_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                                         deleted INTEGER DEFAULT 0,
                                         CONSTRAINT fk_standards_company FOREIGN KEY (company_id) REFERENCES company(id)
);
CREATE INDEX idx_standards_company_id ON standards(company_id);
CREATE INDEX idx_standards_name ON standards(name);
CREATE INDEX idx_standards_create_time ON standards(create_time);
CREATE INDEX idx_standards_update_time ON standards(update_time);

-- 提示词表（新增）
CREATE TABLE IF NOT EXISTS prompts (
                                       id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                       name VARCHAR(128) NOT NULL,
                                       prompt TEXT NOT NULL,
                                       advisor varchar(50) NOT NULL,
                                       description TEXT,
                                       enabled BOOLEAN DEFAULT TRUE,
                                       company_id BIGINT,
                                       user_id BIGINT,
                                       create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                                       update_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                                       deleted INTEGER DEFAULT 0,
                                       CONSTRAINT fk_prompts_company FOREIGN KEY (company_id) REFERENCES company(id),
                                       CONSTRAINT fk_prompts_user FOREIGN KEY (user_id) REFERENCES users(id)
);
CREATE INDEX idx_prompts_name ON prompts(name);
CREATE INDEX idx_prompts_scene ON prompts(advisor);
CREATE INDEX idx_prompts_company_id ON prompts(company_id);
CREATE INDEX idx_prompts_user_id ON prompts(user_id);
CREATE INDEX idx_prompts_enabled ON prompts(enabled);
CREATE INDEX idx_prompts_create_time ON prompts(create_time);
CREATE INDEX idx_prompts_update_time ON prompts(update_time);


-- 创建聊天会话表
CREATE TABLE chat_sessions (
                               id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                               user_id BIGINT NOT NULL,
                               company_id BIGINT NOT NULL,
                               scene VARCHAR(20) NOT NULL,
                               title VARCHAR(255),
                               status VARCHAR(20) DEFAULT 'ACTIVE',
                               last_active_time TIMESTAMP,
                               current_stage VARCHAR(50) DEFAULT 'IDLE',
                               collected_params TEXT,
                               create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                               update_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                               deleted INTEGER DEFAULT 0,
                               CONSTRAINT fk_session_user FOREIGN KEY (user_id) REFERENCES users(id),
                               CONSTRAINT fk_session_company FOREIGN KEY (company_id) REFERENCES company(id)
);

CREATE INDEX idx_session_user ON chat_sessions(user_id);
CREATE INDEX idx_session_company ON chat_sessions(company_id);
CREATE INDEX idx_session_status ON chat_sessions(status);
CREATE INDEX idx_session_scene ON chat_sessions(scene);
CREATE INDEX idx_session_last_active_time ON chat_sessions(last_active_time);
CREATE INDEX idx_session_current_stage ON chat_sessions(current_stage);
CREATE INDEX idx_session_collected_params ON chat_sessions(collected_params);
CREATE INDEX idx_session_create_time ON chat_sessions(create_time);
CREATE INDEX idx_session_update_time ON chat_sessions(update_time);

-- 创建聊天信息表
CREATE TABLE chat_messages (
                               id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                               session_id BIGINT NOT NULL,
                               role VARCHAR(20) NOT NULL,
                               content TEXT,
                               message_type VARCHAR(32),
                               file_url VARCHAR(512),
                               metadata JSONB,
                               create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                               deleted INTEGER DEFAULT 0,
                               CONSTRAINT fk_message_session FOREIGN KEY (session_id) REFERENCES chat_sessions(id)
);

CREATE INDEX idx_message_session ON chat_messages(session_id);
CREATE INDEX idx_message_role ON chat_messages(role);
CREATE INDEX idx_message_type ON chat_messages(message_type);
CREATE INDEX idx_message_create_time ON chat_messages(create_time);

-- 创建RAG文件表
CREATE TABLE IF NOT EXISTS rag_files (
                                         id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                         scene VARCHAR(50) NOT NULL,
                                         file_name VARCHAR(255) NOT NULL,
                                         file_path VARCHAR(512) NOT NULL,
                                         file_size BIGINT NOT NULL,
                                         mime_type VARCHAR(128) NOT NULL,
                                         status VARCHAR(32) DEFAULT 'ENABLED',
                                         user_id BIGINT,
                                         company_id BIGINT,
                                         description TEXT,
                                         create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                                         update_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                                         deleted INTEGER DEFAULT 0,
                                         CONSTRAINT fk_ragfile_user FOREIGN KEY (user_id) REFERENCES users(id),
                                         CONSTRAINT fk_ragfile_company FOREIGN KEY (company_id) REFERENCES company(id)
);
CREATE INDEX idx_ragfile_scene ON rag_files(scene);
CREATE INDEX idx_ragfile_user_id ON rag_files(user_id);
CREATE INDEX idx_ragfile_company_id ON rag_files(company_id);
CREATE INDEX idx_ragfile_status ON rag_files(status);
CREATE INDEX idx_ragfile_create_time ON rag_files(create_time);
CREATE INDEX idx_ragfile_file_name ON rag_files(file_name);

-- 政策文档表（用于 RAG 矢量检索）
CREATE TABLE IF NOT EXISTS policy_documents (
                                                id          SERIAL PRIMARY KEY,
                                                company_id  BIGINT NOT NULL,
                                                dept_id     BIGINT,
                                                content     TEXT NOT NULL,
                                                embedding   VECTOR(1536),  -- text-embedding-v3 输出维度，需与 spring.ai.dashscope.embedding.options.dimensions 配置保持一致
                                                metadata    JSONB,
                                                scene       VARCHAR(50),
                                                enabled     BOOLEAN DEFAULT TRUE,
                                                create_time  TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                                                update_time  TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                                                CONSTRAINT fk_policy_company FOREIGN KEY (company_id) REFERENCES company(id),
                                                CONSTRAINT fk_policy_dept FOREIGN KEY (dept_id) REFERENCES departments(id)
);

-- 创建 HNSW 索引（用于向量相似度检索）
CREATE INDEX IF NOT EXISTS policy_documents_embedding_idx
    ON policy_documents USING hnsw (embedding vector_cosine_ops);

-- 创建公司和部门索引（加速隔离查询）
CREATE INDEX IF NOT EXISTS idx_policy_company_id ON policy_documents(company_id);
CREATE INDEX IF NOT EXISTS idx_policy_dept_id ON policy_documents(dept_id);
CREATE INDEX IF NOT EXISTS idx_policy_scene ON policy_documents(scene);
CREATE INDEX IF NOT EXISTS idx_policy_enabled ON policy_documents(enabled);
CREATE INDEX IF NOT EXISTS idx_policy_create_time ON policy_documents(create_time);
CREATE INDEX IF NOT EXISTS idx_policy_create_time ON policy_documents(update_time);

-- ================================================
-- 4. 创建常用索引（加速查询）
-- ================================================


-- JSONB 字段索引
CREATE INDEX idx_order_journey ON orders USING GIN(journey);
CREATE INDEX idx_journey_tickets ON journeys USING GIN(tickets);

-- ================================================
-- 5. 初始化默认数据（DML）
-- ================================================

-- 清空表（开发测试用，正式环境请注释掉）
TRUNCATE TABLE approvals, tickets, journeys, orders, passengers, employees, departments, company, users, standards, prompts RESTART IDENTITY CASCADE;

-- 插入默认企业（密码为 123456 的 BCrypt 加密值）
INSERT INTO company (id, name, description, auto_approve, user_name, password, create_time, update_time, deleted)
VALUES (1, '博亚科技 (香港) 有限公司', '智能商旅内部测试企业', false, 'boonya', '123456', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0);

-- 插入默认部门（树形结构）
INSERT INTO departments (id, parent_id, company_id, name, description, create_time, update_time, deleted)
VALUES
    (1, 0, 1, '总部', '公司总部', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0),
    (2, 1, 1, '技术部', '研发与运维', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0),
    (3, 1, 1, '行政部', '人事行政', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0);

-- 插入默认用户（密码为 123456 的 BCrypt 加密值示例，实际请替换为真实加密）
INSERT INTO users (id, username, password, email, phone, create_time, update_time, deleted, roles)
VALUES (1, 'admin', '$2a$10$Atuh4yh0XFi2lz/209Emd.WG8ZjJ.isdkpml2opvdd/LdYP266gTi', 'boonya@163.com', '18081976691', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0, 'ROLE_SUPER_ADMIN,ROLE_ADMIN');

INSERT INTO users (id, username, password, email, phone, create_time, update_time, deleted, roles)
VALUES (2, 'boonya', '$2a$10$Atuh4yh0XFi2lz/209Emd.WG8ZjJ.isdkpml2opvdd/LdYP266gTi', 'boonya@163.com', '18081976691', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0, 'ROLE_ADMIN');

-- 插入默认员工（关联用户和部门）
INSERT INTO employees (id, company_id, department_id, user_id, position, name, employee_no, entry_date, is_primary, create_time, update_time, deleted)
VALUES (1, 1, 2, 1, '普通员工','赵大', 'EMP0001', '2024-01-01', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0);

INSERT INTO employees (id, company_id, department_id, user_id, position, employee_no, entry_date, is_primary, create_time, update_time, deleted)
VALUES (2, 1, 1, 2, '普通员工','钱二', 'EMP0002', '2024-01-01', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0);

-- 插入审批记录数据
INSERT INTO approvals (id, order_no, applicant_id, approver_id, status, remark, create_time, update_time, deleted)
VALUES
    (1, 'ORD20260312001', 1, 2, 'APPROVED', '同意，行程合理', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0),
    (2, 'ORD20260312002', 1, 2, 'SUBMITTED', '已提交审批', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0);

-- 插入一条测试订单（机票）
INSERT INTO orders (id, company_id, order_no, user_id, username, order_type, amount, status, pay_time, pay_type, refundable, refund_amount, create_time, update_time, deleted,approval_id)
VALUES
    (1, 1, 'ORD20260312001', 1, 'admin', 'FLIGHT', 1280.00, 'PENDING_PAYMENT', NULL, NULL, true, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0, 1),
    (2, 1, 'ORD20260312002', 1, 'admin', 'FLIGHT', 889.00, 'PENDING_PAYMENT', NULL, NULL, true, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0, 2);

-- 插入默认提示词配置（按场景分类）
INSERT INTO prompts (id, name, prompt, advisor, description, enabled, company_id, user_id, create_time, update_time, deleted)
VALUES
    -- 差旅政策咨询场景
    (1, '差旅政策咨询', '你是一名专业的差旅政策顾问，请根据公司的差旅标准为员工提供差旅政策咨询服务。回答应简洁明了，重点突出费用标准和报销流程。', 'POLICY', '用于回答员工关于差旅政策的咨询', true, 1, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0),

    -- 行程规划场景
    (2, '行程规划助手', '你是一名经验丰富的差旅规划专家，请根据员工的出差目的地、时间和预算，提供最优的行程安排建议，包括交通、住宿等。', 'PLANNING', '帮助员工规划出差行程', true, 1, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0),

    -- 费用预估场景
    (3, '费用预估顾问', '你是一名财务顾问，请根据历史数据和公司差旅标准，为员工提供出差费用预估服务，包括交通费、住宿费、餐饮补贴等。', 'COSTS', '提供出差费用预估', true, 1, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0),

    -- 酒店推荐场景
    (4, '酒店推荐助手', '你是一名酒店预订专家，请根据员工的出差地点、预算和偏好，推荐合适的酒店，并说明酒店的设施、交通和价格优势。', 'HOTEL', '提供酒店预订建议', true, 1, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0),

    -- 机票预订场景
    (5, '机票预订顾问', '你是一名机票预订专家，请根据员工的出行时间、目的地和预算，推荐最优的航班选择，包括直飞、中转等不同方案。', 'FLIGHT', '提供机票预订建议', true, 1, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0),

    -- 火车票务场景
    (6, '火车票务助手', '你是一名火车票务专家，请根据员工的出行需求，提供高铁、动车、普速列车等不同车次的建议和票务信息。', 'TRAIN', '提供火车票务咨询', true, 1, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0),

    -- 用车服务场景
    (7, '用车服务顾问', '你是一名用车服务专家，请根据员工的接送机、市内交通等需求，推荐合适的用车方案，包括网约车、出租车、包车等。', 'CAR', '提供用车服务建议', true, 1, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0),

    -- 审批流程场景
    (8, '审批流程助手', '你是一名审批流程专家，请为员工解答差旅审批流程、审批人、审批时效等问题，并提供流程优化建议。', 'APPROVAL', '提供审批流程咨询', true, 1, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0),

    -- 报销指南场景
    (9, '报销指南顾问', '你是一名财务报销专家，请指导员工如何正确填写报销单、准备报销凭证、了解报销时效和注意事项。', 'REIMBURSEMENT', '提供报销流程指导', true, 1, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0),

    -- 安全提示场景
    (10, '出行安全助手', '你是一名旅行安全专家，请为员工提供出差目的地的安全提示、健康建议、紧急联系方式等信息。', 'SAFETY', '提供出行安全建议', true, 1, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0);

-- 插入差标标准数据
INSERT INTO standards (company_id, name, content, flight_max_price, month_max_price, year_max_price, description, deleted)
VALUES
    (1, '机票经济舱标准', '员工出差乘坐飞机，原则上应选择经济舱。机票价格超过 3000 元需提前申请。鼓励提前预订以获取更优惠价格。', 3000.00, 5000.00, 20000.00, '机票经济舱标准，最高 3000 元', 0),
    (1, '机票特殊舱位申请', '因特殊情况需乘坐公务舱或头等舱的，须提前 3 个工作日提交书面申请，经部门负责人和财务总监审批后方可预订。', 5000.00, 10000.00, 50000.00, '特殊情况下可申请更高舱位', 0);

-- 酒店场景差标
INSERT INTO standards (company_id, name, content, hotel_max_price, month_max_price, year_max_price, description, deleted)
VALUES
    (1, '一线城市酒店标准', '北京、上海、广州、深圳等一线城市，酒店住宿标准为每晚不超过 1000 元。如遇展会期间或旅游旺季，可申请上浮 30%。', 1000.00, 5000.00, 20000.00, '一线城市酒店每晚最高 1000 元', 0),
    (1, '二线城市酒店标准', '省会城市、计划单列市等二线城市，酒店住宿标准为每晚不超过 600 元。其他城市标准为每晚不超过 400 元。', 600.00, 5000.00, 20000.00, '二线城市酒店每晚最高 600 元', 0);

-- 火车场景差标
INSERT INTO standards (company_id, name, content, train_max_price, month_max_price, year_max_price, description, deleted)
VALUES
    (1, '高铁动车标准', '员工出差乘坐高铁或动车，应选择二等座。特殊情况需乘坐一等座的，须经部门负责人审批。高铁票价超过 800 元需提前申请。', 800.00, 5000.00, 20000.00, '高铁动车二等座标准', 0),
    (1, '普速列车标准', '乘坐普速列车出差，可选择硬卧或软卧。夕发朝至的列车优先选择卧铺，以保障休息。', 500.00, 5000.00, 20000.00, '普速列车卧铺标准', 0);

-- 用车场景差标
INSERT INTO standards (company_id, name, content, car_max_price, month_max_price, year_max_price, description, deleted)
VALUES
    (1, '市内交通标准', '员工出差期间市内交通，优先选择地铁、公交等公共交通工具。确需打车或网约车的，单次不超过 200 元，凭发票报销。', 200.00, 5000.00, 20000.00, '市内交通单次最高 200 元', 0),
    (1, '接送机用车标准', '员工出差往返机场，可选择打车、网约车或接送机服务。携带大件行李或多人同行时可申请包车服务。', 300.00, 5000.00, 20000.00, '接送机用车标准', 0);

-- 插入聊天会话数据
INSERT INTO chat_sessions (id, user_id, company_id, scene, title, status, last_active_time, create_time, update_time, deleted)
VALUES
    (1, 1, 1, 'POLICY', '差旅政策咨询 - 2026-03-15', 'ACTIVE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0),
    (2, 1, 1, 'PLANNING', '北京出差行程规划', 'ACTIVE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0),
    (3, 1, 1, 'COSTS', '上海展会费用预估', 'ACTIVE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0),
    (4, 2, 1, 'FLIGHT', '深圳机票预订咨询', 'ACTIVE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0),
    (5, 2, 1, 'HOTEL', '杭州酒店推荐', 'CLOSED', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0);

-- 插入聊天信息数据
INSERT INTO chat_messages (id, session_id, role, content, message_type, file_url, metadata, create_time, deleted)
VALUES
    -- 会话 1：差旅政策咨询
    (1, 1, 'USER', '请问公司对于一线城市住宿的标准是多少？', 'TEXT', NULL, '{}', CURRENT_TIMESTAMP, 0),
    (2, 1, 'ASSISTANT', '根据公司差旅政策，一线城市的住宿标准为每天 500 元。一线城市包括北京、上海、广州、深圳。如果实际住宿费用超出标准，超出部分需要自理。', 'TEXT', NULL, '{"source": "standards"}', CURRENT_TIMESTAMP, 0),
    (3, 1, 'USER', '那餐饮补贴呢？', 'TEXT', NULL, '{}', CURRENT_TIMESTAMP, 0),
    (4, 1, 'ASSISTANT', '国内出差餐饮补贴标准为：早餐 30 元/天，午餐 50 元/天，晚餐 50 元/天，合计 130 元/天。海外出差为 210 元/天。', 'TEXT', NULL, '{"source": "standards"}', CURRENT_TIMESTAMP, 0),

    -- 会话 2：行程规划
    (5, 2, 'USER', '我下周要去北京出差 3 天，帮我规划一下行程', 'TEXT', NULL, '{"destination": "北京", "duration": 3}', CURRENT_TIMESTAMP, 0),
    (6, 2, 'ASSISTANT', '好的，为您规划北京 3 天出差行程：\n\n第一天：\n- 上午：抵达北京，办理酒店入住\n- 下午：拜访客户 A 公司\n- 晚上：整理会议资料\n\n第二天：\n- 全天：参加行业峰会\n- 晚上：商务晚宴\n\n第三天：\n- 上午：拜访客户 B 公司\n- 下午：返程\n\n预计总费用：交通 2000 元 + 住宿 1500 元 + 餐饮 390 元 = 3890 元', 'TEXT', NULL, '{"estimated_cost": 3890}', CURRENT_TIMESTAMP, 0),

    -- 会话 3：费用预估
    (7, 3, 'USER', '去上海参加展会 5 天，大概需要多少费用？', 'TEXT', NULL, '{"destination": "上海", "days": 5, "purpose": "展会"}', CURRENT_TIMESTAMP, 0),
    (8, 3, 'ASSISTANT', '根据上海 5 天展会出差，费用预估如下：\n\n1. 交通费：往返机票约 2400 元\n2. 住宿费：5 天 × 500 元/天 = 2500 元（上海为一线城市）\n3. 餐饮补贴：5 天 × 130 元/天 = 650 元\n4. 市内交通：5 天 × 100 元/天 = 500 元\n5. 展会注册费：约 2000 元\n\n总计：约 8050 元', 'TEXT', NULL, '{"breakdown": {"flight": 2400, "hotel": 2500, "food": 650, "transport": 500, "registration": 2000}}', CURRENT_TIMESTAMP, 0),

    -- 会话 4：机票预订
    (9, 4, 'USER', '明天去深圳的航班有哪些推荐？', 'TEXT', NULL, '{"destination": "深圳", "date": "2026-03-16"}', CURRENT_TIMESTAMP, 0),
    (10, 4, 'ASSISTANT', '为您查询到明天（3 月 16 日）前往深圳的推荐航班：\n\n1. CA1335 08:00-11:30 经济舱 1680 元（推荐，时间好）\n2. ZH9103 10:30-14:00 经济舱 1520 元（性价比高）\n3. MU5341 14:30-18:00 经济舱 1380 元（最便宜）\n4. CZ3584 18:00-21:30 经济舱 1450 元\n\n建议选择 CZ3584，价格实惠且不影响当天工作。', 'TEXT', NULL, '{"flights": ["CA1335", "ZH9103", "MU5341", "CZ3584"]}', CURRENT_TIMESTAMP, 0);

INSERT INTO rag_files (id,scene, file_name, file_path, file_size, mime_type, status, user_id, company_id, description, create_time, update_time, deleted)
VALUES
    (1, 'QA', '公司差旅政策手册.pdf', '/rag-files/company/travel-policy-2024.pdf', 2458624, 'application/pdf', 'ENABLED', 1, 1, '公司最新差旅政策与报销标准', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0),

    (2,'HOTEL', '国内酒店协议价格表.xlsx', '/rag-files/company/hotel-rates-2024.xlsx', 1024768, 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet', 'ENABLED', 1, 1, '2024 年国内主要城市协议酒店价格清单', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0),

    (3,'FLIGHT', '航空公司合作优惠方案.docx', '/rag-files/company/airline-discount-2024.docx', 524288, 'application/vnd.openxmlformats-officedocument.wordprocessingml.document', 'ENABLED', 2, 1, '与合作航空公司的折扣协议及预订流程', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0);

-- 插入默认政策文档数据（示例）
INSERT INTO policy_documents (company_id, dept_id, content, metadata, scene, enabled)
VALUES
    -- 公司级通用差旅政策
    (1, NULL,
     '公司员工出差交通标准：一线城市飞机经济舱全价、高铁一等座；二线城市及以下高铁二等座。住宿标准：一线城市 500 元/天，二线城市 350 元/天，其他城市 250 元/天。餐饮补贴：国内 130 元/天，海外 210 元/天。',
     '{"version": "2024-v1", "author": "行政部", "keywords": ["交通", "住宿", "餐饮", "差标"]}',
     'TRAVEL_POLICY', true),

    -- 技术部专属政策
    (1, 2,
     '技术部员工参加技术会议可申请特殊预算，包括会议注册费、差旅费等。年度技术会议预算上限为每人 2 万元。需提前 2 周提交申请，经部门负责人和技术总监审批。',
     '{"version": "2024-v1", "author": "技术部", "keywords": ["技术会议", "预算", "审批"]}',
     'TECH_CONFERENCE', true),

    -- 财务部政策
    (1, NULL,
     '所有费用报销需在费用发生后 30 天内提交，逾期不予受理。报销单需附正规发票，电子发票需打印并签字。单笔超过 5000 元的支出需提前申请。',
     '{"version": "2024-v2", "author": "财务部", "keywords": ["报销", "发票", "时效"]}',
     'FINANCE_RULES', true);